### ISSUE TITLE
Actividad 1 Mapa Mental_Maribel Santiago Bautista 1°BS

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-1-mapa-mental-santiagomary1004#1]
[Investigacion documental - Mapa Mental 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-santiagomary1004/files/9483756/Investigacion.documental.-.Mapa.Mental.1.pdf)

**Comment by AmeliReyesHernandez** [comment]
17.8 de 20

**Comment by AmeliReyesHernandez** [comment]
16.6

**Comment by AmeliReyesHernandez** [comment]
16.6

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
